site_name: Acute Support Documentation Page
site_description: "Acute Support Documentation Page"

copyright: Copyright &copy; 2025 - 2026 Acute Technology Inc.

theme:
  language: en
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.tabs
    - content.footnote.tooltips
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  navigation_depth: 3
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
      accent: deep purple 

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh-TW
          name: 中文(繁體)
          build: true
        - locale: zh
          name: 中文(简体)
          build: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: false
            docstring_style: google
            docstring_section_style: table
            # heading_level: 3
            show_signature_annotations: false  # Hides type annotations to save space
            separate_signature: true  # Separates signature from description
            # extensions:
            # - griffe_typingdoc
            # show_symbol_type_heading: true
            # show_root_heading: true
            # show_if_no_docstring: true
            # preload_modules:
            # - httpx
            # - starlette
            # inherited_members: true
            # members_order: source
            # separate_signature: true
            # unwrap_annotated: true
            # filters:
            # - '!^_'
            # merge_init_into_class: true
            # docstring_section_style: spacy
            # signature_crossrefs: true
            # show_symbol_type_heading: true
            # show_symbol_type_toc: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acute-technology-inc
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Acute-Technology-Inc-%E7%9A%87%E6%99%B6%E7%A7%91%E6%8A%80/100057450009131/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Acute_Tech_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/acute-technology-taiwan
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/AcuteTechnologyInc
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/522011819

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - markdown.extensions.nl2br
  - pymdownx.caret  
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.critic:
      mode: accept
  - pymdownx.keys
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      toc_depth: 3

# Only enable strict mode in CI/CD pipelines
# strict: true

validation:
  # Warn about Markdown files not listed in the nav.
  omitted_files: info

  # If a link is /foo/bar.md,
  # turn it into relative to the docs/ directory.
  absolute_links: relative_to_docs

  # Warn about broken internal links to pages or anchors.
  unrecognized_links: warn
  anchors: warn

draft_docs: |
  protocol-analyzer/
  specification/
  trigger/
  troubleshooting/
  software/installation.md
  logic-analyzer/drafts/
  protocols/

nav:
  - Home: index.md
  - Getting Started:
    # - Hardware Configuration: hardware-configuration.md
    - Software Installation:
      - Download: software/download.md
      - Install: software/installation.md
      # - Driver Install: software/driver.md
      # - Miscellaneous: software/miscellaneous.md
    - Sessions: 
      - Working with multiple sessions: software/sessions.md
    # - Specifications: 
    #   - Specifications: specification/specifications.md
  - Protocol Exerciser:
    - protocol-exerciser/index.md
    - Protocols:
      - I2C:
        - protocol-exerciser/i2c/i2c.md
        - Quick Start: protocol-exerciser/i2c/quick-start.md
        - Bus Select: protocol-exerciser/i2c/bus-select.md
        - Px Pair Settings: protocol-exerciser/i2c/px-pair-settings.md
        - Add Internal Node: protocol-exerciser/i2c/add-internal-node.md
        - Controller Mode: protocol-exerciser/i2c/controller.md
        - Target Mode: protocol-exerciser/i2c/target.md
      - MIPI I3C:
        - protocol-exerciser/i3c/i3c.md
        - Quick Start: protocol-exerciser/i3c/quick-start.md
        - Bus Select: protocol-exerciser/i3c/bus-select.md
        - Px Pair Settings: protocol-exerciser/i3c/px-pair-settings.md
        - Controller Mode: protocol-exerciser/i3c/controller.md
        - Target Mode: protocol-exerciser/i3c/target.md
        - Internal Node: protocol-exerciser/i3c/internal-node.md
        - Wizard: protocol-exerciser/i3c/wizard.md
      - UART:
        - protocol-exerciser/uart/uart.md
        - Quick Start: protocol-exerciser/uart/quick-start.md
        - Bus Select: protocol-exerciser/uart/functions.md
        - Px Pair Settings: protocol-exerciser/uart/px-pair-settings.md
  - Logic Analyzer:
    - logic-analyzer/index.md
    - Getting Started:
      - Overview: logic-analyzer/interface-guide.md
      - Quick Start: logic-analyzer/quick-start.md
    - Capturing Data:
      - Capture settings: logic-analyzer/capture-settings.md
      - Trigger settings: logic-analyzer/trigger-settings.md
      - Advanced capture settings: logic-analyzer/advanced-capture.md
    - Analyzing Waveforms:
      - Navigate the data: logic-analyzer/navigate-data.md
      - Channel labels: logic-analyzer/channel-labels.md
      - Interact with cursors: logic-analyzer/cursor.md
      - Navigate the report: logic-analyzer/navigate-report.md
    - File Operations:
      - Open & Save Files: logic-analyzer/file-operations.md
      - Export Data: logic-analyzer/export-data.md
    - Advanced Features:
      - Power Sequence Validation: logic-analyzer/power-sequence-validation.md
      - Stack External Oscilloscope: logic-analyzer/stack-oscilloscope.md
    - Preferences:
      - System environment options: logic-analyzer/preferences.md
      - Keyboard shortcuts: logic-analyzer/keyboard-shortcuts.md
  # - Protocol Analyzer:
  #   - protocol-analyzer/index.md
  #   - Capturing Data:
  #     - Protocol Settings: protocol-analyzer/protocol-settings.md
  #     - Operating Modes: protocol-analyzer/operating-modes.md
  #     - Capture Modes: protocol-analyzer/capture-modes.md
  #   - Navigation:
  #     - Show Waveforms: protocol-analyzer/show-waveforms.md
  #     - Search: protocol-analyzer/search.md
  #     - Detail & Statistics: protocol-analyzer/detail-statistics.md
  #     - Window Management: protocol-analyzer/window-management.md
  #     - Cursor: protocol-analyzer/cursor.md
  #   - Exporting Data:
  #     - File Operations: protocol-analyzer/file-operations.md
  #   - Preferences:
  #     - Keyboard shortcuts: protocol-analyzer/keyboard-shortcuts.md
  - Supported Protocols:
    - protocols/index.md
    # - Curated List:
    #   - 1-Wire: protocols/1-wire.md
    #   - 10BASE-T1S: protocols/10base-t1s.md
    #   - 3-Wire: protocols/3-wire.md
    #   - 7-Segment: protocols/7-segment.md
    #   - A/D Converter: protocols/ad-converter.md
    #   - AcceleroMeter: protocols/accmeter.md
    #   - AD-Mux Flash: protocols/ad-mux-flash.md
    #   - APML: protocols/apml.md
    #   - AVSBus: protocols/avsbus.md
    #   - BiSS-C: protocols/biss-c.md
    #   - BSD: protocols/bsd.md
    #   - BT1120: protocols/bt1120.md
    #   - CAN FD: protocols/can-fd.md
    #   - CEC: protocols/cec.md
    #   - Closed Caption: protocols/closed-caption.md
    #   - Codec SSI: protocols/codec-ssi.md
    #   - CvTktTab: protocols/cvtktab.md
    #   - DALI: protocols/dali.md
    #   - DDC/EDID: protocols/ddc-edid.md
    #   - DMX512: protocols/dmx512.md
    #   - DisplayPort AUX: protocols/dp-auxch.md
    #   - eSPI: protocols/espi.md
    #   - FlexRay: protocols/flexray.md
    #   - HD Audio: protocols/hd-audio.md
    #   - HDLC: protocols/hdlc.md
    #   - HDQ: protocols/hdq.md
    #   - HID over I2C: protocols/hid-over-i2c.md
    #   - HID over SPI: protocols/hid-over-spi.md
    #   - HTSensor: protocols/htsensor.md
    #   - I2C: protocols/i2c.md
    #   - I2C EEPROM: protocols/i2c-eeprom.md
    #   - I2C User Defined: protocols/i2c-user-defined.md
    #   - I2S: protocols/i2s.md
    #   - I80: protocols/i80.md
    #   - IDE: protocols/ide.md
    #   - IO-Link: protocols/iolink.md
    #   - IrDA: protocols/irda.md
    #   - ISELED RGB LED: protocols/iseled-rgb-led.md
    #   - ITU-R BT.656: protocols/itu-r-bt656.md
    #   - JTAG: protocols/jtag.md
    #   - JVC IR: protocols/jvc-ir.md
    #   - LCD1602: protocols/lcd1602.md
    #   - LED Control: protocols/led-ctrl.md
    #   - LIN: protocols/lin.md
    #   - Line Decoding: protocols/line-decoding.md
    #   - Line Encoding: protocols/line-encoding.md
    #   - Lissajous: protocols/lissajous.md
    #   - LPC: protocols/lpc.md
    #   - LPT: protocols/lpt.md
    #   - M-Bus: protocols/mbus.md
    #   - MDDI: protocols/mddi.md
    #   - MDIO: protocols/mdio.md
    #   - MIPI CSI: protocols/mipi-csi.md
    #   - MIPI DSI: protocols/mipi-dsi.md
    #   - MIPI I3C: protocols/mipi-i3c.md
    #   - MIPI RFFE: protocols/mipi-rffe.md
    #   - MIPI SoundWire: protocols/mipi-soundwire.md
    #   - MIPI SPMI: protocols/mipi-spmi.md
    #   - Math: protocols/math.md
    #   - MHL-CBUS: protocols/mhl-cbus.md
    #   - Microchip SWI: protocols/microchip-swi.md
    #   - Microwire: protocols/microwire.md
    #   - Mini/Micro LED: protocols/mini-micro-led.md
    #   - MII/RMII/RGMII/GMII:
    #     - protocols/mii/index.md
    #     - MII: protocols/mii/mii.md
    #     - RMII: protocols/mii/rmii.md
    #     - GMII: protocols/mii/gmii.md
    #     - RGMII: protocols/mii/rgmii.md
    #   - MMC/eMMC: protocols/mmc-emmc.md
    #   - Modbus: protocols/modbus.md
    #   - NAND Flash: protocols/nand-flash.md
    #   - NEC IR: protocols/nec-ir.md
    #   - OA3P (OPEN Alliance 3-Pin): protocols/oa3p-pmd.md
    #   - OATC6 over SPI: protocols/oatc6-over-spi.md
    #   - PCM: protocols/pcm.md
    #   - PECI: protocols/peci.md
    #   - PDM: protocols/pdm.md
    #   - PMBus: protocols/pmbus.md
    #   - PROFIBUS: protocols/profibus.md
    #   - PS/2: protocols/ps2.md
    #   - PWM: protocols/pwm.md
    #   - QEI: protocols/qei.md
    #   - Qi: protocols/qi.md
    #   - QSPI: protocols/qspi.md
    #   - RC-5: protocols/rc5.md
    #   - RC-6: protocols/rc6.md
    #   - RT-SWI: protocols/rt-swi.md
    #   - RGB Interface: protocols/rgb-if.md
    #   - SDIO/SD 3.0: protocols/sdio-sd3.md
    #   - SDQ: protocols/sdq.md
    #   - SENT: protocols/sent.md
    #   - Serial Flash: protocols/serial-flash.md
    #   - Serialized IRQ: protocols/serialized-irq.md
    #   - SGPIO: protocols/sgpio.md
    #   - Smart Card (ISO 7816): protocols/smart-card-iso7816.md
    #   - SMBus: protocols/smbus.md
    #   - SMI: protocols/smi.md
    #   - S/PDIF: protocols/spdif.md
    #   - SPI: protocols/spi.md
    #   - SPI NAND: protocols/spi-nand.md
    #   - ST7669: protocols/st7669.md
    #   - SSI: protocols/ssi.md
    #   - SVID: protocols/svid.md
    #   - SVI2: protocols/svi2.md
    #   - SWD: protocols/swd.md
    #   - SWIM: protocols/swim.md
    #   - SWP: protocols/swp.md
    #   - TDM: protocols/tdm.md
    #   - UART: protocols/uart.md
    #   - UFCS: protocols/ufcs.md
    #   - ULPI: protocols/ulpi.md
    #   - UNI/O: protocols/unio.md
    #   - USB 1.1: protocols/usb1-1.md
    #   - USB Power Delivery: protocols/usb-pd.md
    #   - USB4/Thunderbolt 3 Sideband: protocols/usb4-tbt3-sb.md
    #   - Wiegand: protocols/wiegand.md
  # - FAQ:
  #   - faq/index.md
  #   - Troubleshooting: 
  #     - How to Use: troubleshooting/additional-resources.md
  #     - Demo Mode: troubleshooting/demo-mode.md
