site_name: Acute Support Documentation Page
site_description: "Acute Support Documentation Page"

copyright: Copyright &copy; 2025 - 2026 Acute Technology Inc.

theme:
  language: en
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.tabs
    - content.footnote.tooltips
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  navigation_depth: 3
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
      accent: deep purple 

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh-TW
          name: 中文(繁體)
          build: true
        - locale: zh
          name: 中文(简体)
          build: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: false
            docstring_style: google
            docstring_section_style: table
            # heading_level: 3
            show_signature_annotations: false  # Hides type annotations to save space
            separate_signature: true  # Separates signature from description
            # extensions:
            # - griffe_typingdoc
            # show_symbol_type_heading: true
            # show_root_heading: true
            # show_if_no_docstring: true
            # preload_modules:
            # - httpx
            # - starlette
            # inherited_members: true
            # members_order: source
            # separate_signature: true
            # unwrap_annotated: true
            # filters:
            # - '!^_'
            # merge_init_into_class: true
            # docstring_section_style: spacy
            # signature_crossrefs: true
            # show_symbol_type_heading: true
            # show_symbol_type_toc: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acute-technology-inc
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Acute-Technology-Inc-%E7%9A%87%E6%99%B6%E7%A7%91%E6%8A%80/100057450009131/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Acute_Tech_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/acute-technology-taiwan
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/AcuteTechnologyInc
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/522011819

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.nl2br
  - pymdownx.caret  
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

nav:
  - Home: index.md
  - Getting Started:
    - Hardware Configuration: hardware-configuration.md
    - Software Installation:
      - Download: software/download.md
      - Install: software/installation.md
      - Driver Install: software/driver.md
      - Miscellaneous: software/miscellaneous.md
    - Specifications: 
      - Specifications: specification/specifications.md
  - Protocol Exerciser:
    - protocol-exerciser/index.md
    - Protocols:
      - I2C:
        - protocol-exerciser/i2c/i2c.md
        - Quick Start: protocol-exerciser/i2c/quick-start.md
        - Bus Select: protocol-exerciser/i2c/bus-select.md
        - Px Pair Settings: protocol-exerciser/i2c/px-pair-settings.md
        - Add Internal Node: protocol-exerciser/i2c/add-internal-node.md
        - Controller Mode: protocol-exerciser/i2c/controller.md
        - Target Mode: protocol-exerciser/i2c/target.md
      - MIPI I3C:
        - protocol-exerciser/i3c/i3c.md
        - Quick Start: protocol-exerciser/i3c/quick-start.md
        - Bus Select: protocol-exerciser/i3c/bus-select.md
        - Px Pair Settings: protocol-exerciser/i3c/px-pair-settings.md
        - Controller Mode: protocol-exerciser/i3c/controller.md
        - Target Mode: protocol-exerciser/i3c/target.md
        - Internal Node: protocol-exerciser/i3c/internal-node.md
        - Wizard: protocol-exerciser/i3c/wizard.md
      - UART:
        - protocol-exerciser/uart/uart.md
        - Quick Start: protocol-exerciser/uart/quick-start.md
        - Bus Select: protocol-exerciser/uart/functions.md
        - Px Pair Settings: protocol-exerciser/uart/px-pair-settings.md
  - Logic Analyzer:
    - logic-analyzer/index.md
    - File Operations: logic-analyzer/file-operations.md
    - Keyboard Shortcuts: logic-analyzer/keyboard-shortcuts.md
    - Capture Settings: logic-analyzer/capture-settings.md
    - Advanced Capture: logic-analyzer/advanced-capture.md
    - Cursor: logic-analyzer/cursor.md
    - Waveform Area: logic-analyzer/waveform-area.md
    - Report Area: logic-analyzer/report-area.md
    - Bus Decode: logic-analyzer/bus-decode.md
    - Timing Check: logic-analyzer/timing-check.md
    - Stack Oscilloscope: logic-analyzer/stack-oscilloscope.md
  - Protocol Analyzer:
    - protocol-analyzer/index.md
    - File Operations: protocol-analyzer/file-operations.md
    - Keyboard Shortcuts: protocol-analyzer/keyboard-shortcuts.md
    - Capture Modes: protocol-analyzer/capture-modes.md
    - Protocol Settings: protocol-analyzer/protocol-settings.md
    - Operating Modes: protocol-analyzer/operating-modes.md
    - Show Waveforms: protocol-analyzer/show-waveforms.md
    - Search: protocol-analyzer/search.md
    - Window Management: protocol-analyzer/window-management.md
    - Detail & Statistics: protocol-analyzer/detail-statistics.md
    - Cursor: protocol-analyzer/cursor.md
  - Decode:
    - decode/index.md
  - Trigger:
    - trigger/index.md
  - Technical Support:
    - technical-support.md
    - Troubleshooting: 
      - How to Use: troubleshooting/additional-resources.md
      - Demo Mode: troubleshooting/demo-mode.md
